{"classFile":"MathRuntimeExceptionTest","className":"MathRuntimeExceptionTest","packages":"org.apache.commons.math.exception","methodInfos":[{"md5":"KNTwK6dOA2OaUqtiTBM6IQ==","methodName":"testMessageChain","parameters":"[]"},{"md5":"kOKmDxo2bvCJxRjgiLOIGg==","methodName":"testNoArgAddMessage","parameters":"[]"}],"addLines":[41,62,63,64,65,66,67,68],"delLines":[41],"type":"MODIFY","path":"src/test/java/org/apache/commons/math/exception/MathRuntimeExceptionTest.java","pro_Commit":"35a0923edfe498c58bfb1e86099fed85fde0c353","pro_Date":"2011-03-15 19:42:23","sha1":"806ff6b89319568c6827b36642fa2bffee4fb571","file_Date":"2011-03-15 19:42:23","projectName":"commons-math","commitID":"35a0923edfe498c58bfb1e86099fed85fde0c353"}