{"classFile":"CloneFailedExceptionTest","className":"CloneFailedExceptionTest","packages":"org.apache.commons.lang3.exception","methodInfos":[{"md5":"zRlCNPTPMz6iH9zjVdyLeg==","methodName":"testThrowingInformativeException","parameters":"[]"},{"md5":"MIY7bHsbhiq1f80jEY+CTg==","methodName":"testThrowingExceptionWithMessage","parameters":"[]"},{"md5":"+eRrutlCJshvl8iRA4ekBg==","methodName":"testThrowingExceptionWithCause","parameters":"[]"},{"md5":"5S8UyHRG2Xue+SuXUSv6LQ==","methodName":"testWithCauseAndMessage","parameters":"[]"},{"md5":"M3GdzbUXnhNw4lIpDRz58Q==","methodName":"testWithoutCause","parameters":"[]"},{"md5":"FCoblFKcwMovj/DU0W0M0A==","methodName":"testWithoutMessage","parameters":"[]"}],"addLines":[19,21,22,23,24,31,32,33,35,38,39,40,42,45,46,47,49,56,60,67,81],"delLines":[19,21,22,23,30,31,35,36,40,41,49,53,60,74],"type":"MODIFY","path":"src/test/java/org/apache/commons/lang3/exception/CloneFailedExceptionTest.java","pro_Commit":"7b6ab58a018b5f6608ea07bc414d3f34a576c6a2","pro_Date":"2010-02-11 07:22:05","sha1":"9a2173e3aa0ffd9cfd439db2bc70d6e19ee7b6c5","file_Date":"2018-10-07 23:28:09","projectName":"commons-lang","commitID":"884d273f4207095f881167b3398fc2a55617ee9a"}